---
- name: Pull image from Docker Hub and deploy
  hosts: all
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image from docker hub
      docker_image:
        name: "rishi2o2o/calculator:latest"
        source: pull
    - name: Start docker service
      service: 
        name: docker
        state: started
    - name: Remove container if it exists
      shell:
        cmd: |
          if [ "$(docker ps -a -q -f name=calc_container)" ]; then
            docker rm calc_container
          fi
    - name: Create container
      shell: docker create --name calc_container rishi2o2o/calculator:latest
