---
- name: Pull image from Docker Hub and deploy
  hosts: localhost
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image from docker hub
      docker_image:
        name: rishi2o2o/calculator:latest
        source: pull
    - name: Start docker service
      service: 
        name: docker
        state: started
    - name: Create container
      shell: docker create --name calc_container rishi2o2o/calculator:latest
